### ISSUE TITLE
Streaming audio vs fully loading

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#52]
Streaming is obviously faster, but has the downside that duration isn't accurate. Fully loading enabled modulation (do we need that?), but increases the loading time significantly.

**Comment by cascer1** [comment]
+1 plz do streams :+1:

**Comment by Mesoptier** [comment]
This is "HTML5 <audio> vs Web Audio API". I've been having loading issues with our current implementation (Web Audio API) for a while now. And we do have a bunch of larger files which can take some noticeable time to load, especially on mobile. Also I don't think that we're realistically going to need the fancy effect stuff. So yeah, I want to switch to streaming HTML5 <audio>.

_But_, as @villermen already mentioned, the duration is often inaccurate, which leads to samples ending too soon (due to an implementation detail of Howler) and our UI displaying wrong information.

Anyway, this is an important (lol) feature so we definitely need to come up with a solution.

**Comment by Mesoptier** [comment]
...

I think I found a [solution](http://stackoverflow.com/questions/18214764/audio-shows-incorrect-track-progress-no-duration), I got it to work locally at least. Expect a PR soon.

**Comment by villermen** [comment]
Resolved in 55dea5eea413ac8bbb5db40208cc7d2ceeab5ff8.
