### ISSUE TITLE
Only use replaceState for URLs

### ISSUE THREAD

**Issue by Mesoptier** [team-thyme/soundboard#85]
Our URLs are for sharing, not for navigating. With that in mind, I think we could do away with all the `pushState`-ing and only use `replaceState`. Only one `pushState` at the beginning so we always have an empty URL to return to.

**Comment by villermen** [comment]
I've been thinking. We don't really need URLs reflected at all, since we only want to use it for sharing. Are there maybe better ways to indicate that this is possible? The most flexible way would of course be to implement a context menu for samples which allows you to copy the link, or make it loop or whatever. This is also the hardest to implement on mobile, and might not really feel intuitive. (?)

Another reason I've been thinking about this is #76. Having the URL removed as soon as the sample stops or with a delay like Chrome's audio icon on tabs, is not very practical for samples that only last a second or less. Having a way to copy the direct link at any point would be better in this case.

What are your thoughts on a context menu or alternative options @Mesoptier?
